version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./php-apache2
            dockerfile: Dockerfile
        depends_on:
          - db
        volumes:
            - ./sources/:/var/www/html/
        ports:
            - 8000:80
            
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: passMySQL
            MYSQL_DATABASE: fruit_shop
            MYSQL_USER: nbp1
            MYSQL_PASSWORD: passMySQL
        ports:
            - "9906:3306"
        volumes: 
            - ./sources/database/fruit_shop.sql:/docker-entrypoint-initdb.d/dump.sql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db