apiVersion: v1
kind: Namespace
metadata:
  name: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: regfruit.azurecr.io/sqlimage:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: passMySQL
            - name: MYSQL_DATABASE
              value: fruit_shop
            - name: MYSQL_USER
              value: nbp1
            - name: MYSQL_PASSWORD
              value: passMySQL
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: default
spec:
  ports:
    - targetPort: 3306
      port: 3306
  selector:
    app: mysql
